apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: docker.io/cristianbueno/backend:11
          ports:
            - containerPort: 8080
          env:
            - name: NOMBRE
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName