---
## EXPOSE (WAITING)
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
spec:
  selector:
    app: backend-deployment
  ports:
    - name: port
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort